--- #YAML:1.0
name:               Bio-Tools-CodonOptTable
version:            1.04
abstract:           A more elaborative way to check the codons usage!
author:
    - Rakesh Kumar Shardiwal <rakesh.shardiwal@gmail.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Bio::DB::GenBank:     0
    Bio::PrimarySeq:      0
    Bio::Root::Root:      0
    Bio::SeqIO:           0
    Bio::Tools::CodonTable:  0
    Bio::Tools::SeqStats:  0
    Data::Dumper:         0
    File::Slurp:          0
    GD::Graph::bars:      0
    Test::More:           0
    Text::Textile:        0
    URI::Escape:          0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
