--- #YAML:1.0
name:                Bio-Tools-CodonOptTable
version:             0.09
abstract:            A more elaborative way to check the codons usage!
license:             ~
author:              
    - Rakesh Kumar Shardiwal <rakesh.shardiwal@gmail.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Bio::DB::GenBank:              0
    Bio::PrimarySeq:               0
    Bio::Root::Root:               0
    Bio::SeqIO:                    0
    Bio::Tools::CodonTable:        0
    Bio::Tools::SeqStats:          0
    Data::Dumper:                  0
    GD::Graph::bars:               0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
